# Assignment-1(Numpy)

In [1]:
import numpy as np

### 1. Write code to create a 4x3 matrix with values ranging from 2 to 13.

In [2]:
arr1 = np.arange(2, 14).reshape(4, 3)
print(arr1)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]
 [11 12 13]]


### 2. Write code to replace the odd numbers by -1 in the array created by using random.randint( 1 , 50,20)

In [3]:
arr2 = np.random.randint(1, 50, 20)
print("Original Array:", arr2)

arr2[arr2 % 2 != 0] = -1
print("After Replacing Odd Numbers:", arr2)

Original Array: [ 8 23 10 28  1  3 32 28 47 12 34 14 47 17 49 34 10 16 44 11]
After Replacing Odd Numbers: [ 8 -1 10 28 -1 -1 32 28 -1 12 34 14 -1 -1 -1 34 10 16 44 -1]


### 3. Perform the following operations on an array of mobile phones prices 6999, 7500, 11999, 27899, 14999, 9999.

#### a. Create a 1d-array of mobile phones prices

In [4]:
prices = np.array([6999, 7500, 11999, 27899, 14999, 9999])
prices

array([ 6999,  7500, 11999, 27899, 14999,  9999])

#### b. Convert this array to float type

In [7]:
prices = prices.astype(float)
prices

array([ 6999.,  7500., 11999., 27899., 14999.,  9999.])

#### c. Append a new mobile having price of 13999 Rs. to this array

In [8]:
prices = np.append(prices, 13999)
prices

array([ 6999.,  7500., 11999., 27899., 14999.,  9999., 13999.])

#### d. Reverse this array of mobile phones prices

In [9]:
prices = prices[::-1]
prices

array([13999.,  9999., 14999., 27899., 11999.,  7500.,  6999.])

#### e. Apply GST of 18% on mobile phones prices and update this array.

In [10]:
prices = prices + (prices * 0.18)
prices

array([16518.82, 11798.82, 17698.82, 32920.82, 14158.82,  8850.  ,
        8258.82])

#### f. Sort the array in descending order of price

In [11]:
prices = np.sort(prices)[::-1]
prices

array([32920.82, 17698.82, 16518.82, 14158.82, 11798.82,  8850.  ,
        8258.82])

#### g. What is the average mobile phone price

In [13]:
avg_price = np.mean(prices)
avg_price

np.float64(15743.560000000001)

#### h. What is the difference b/w maximum and minimum price

In [14]:
price_diff = np.max(prices) - np.min(prices)
price_diff

np.float64(24662.0)

### 4. Find out the indices of non zero element in given array [1,2,0,0,4,0]

In [15]:
arr4 = np.array([1, 2, 0, 0, 4, 0])

indices = np.nonzero(arr4)
indices

(array([0, 1, 4]),)