# Assignment-2(Numpy)

In [1]:
import numpy as np

### 1. Create a NumPy array containing integers from 0 to 9.

In [2]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 2. Create a NumPy array from a given Python list [10, 20, 30, 40, 50].

In [4]:
arr = np.array([10, 20, 30, 40, 50])
arr

array([10, 20, 30, 40, 50])

### 3. Create a 2D array (3x3) with values ranging from 0 to 8.

In [5]:
arr = np.arange(9).reshape(3, 3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 4. Given a 2D array, find its shape and size. Create a 5x4 array with random integers between 1 and 100, and print the shape and size.

In [6]:
arr = np.random.randint(1, 101, size=(5, 4))
arr.shape
arr.size

20

### 5. Create a 3x3 array of integers and access:

In [8]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### a. The second element of the first row.

In [9]:
arr[0, 1] 

np.int64(2)

#### b. The third column of the 2nd row.

In [10]:
arr[1, 2] 

np.int64(6)

#### c. A subarray with the first two rows and last two columns.

In [11]:
arr[:2, 1:]  

array([[2, 3],
       [5, 6]])

### 6. Create a 1D array of 12 elements. Reshape it into a 3x4 2D array.

In [12]:
arr = np.arange(1, 13).reshape(3, 4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### 7. Reshape a 3x3 matrix into a 1D array.

In [13]:
arr = np.arange(1, 10).reshape(3, 3).reshape(-1)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### 8. Create two arrays of shape (2, 3): arr1 and arr2. Perform element-wise addition, subtraction, multiplication, and division on them.

In [14]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[6,5,4],[3,2,1]])

In [16]:
arr1 + arr2

array([[7, 7, 7],
       [7, 7, 7]])

In [17]:
arr1 - arr2

array([[-5, -3, -1],
       [ 1,  3,  5]])

In [18]:
arr1 * arr2

array([[ 6, 10, 12],
       [12, 10,  6]])

In [19]:
arr1 / arr2

array([[0.16666667, 0.4       , 0.75      ],
       [1.33333333, 2.5       , 6.        ]])

### 9. Use NumPy's built-in functions to compute the sum, mean, and standard deviation of a given array.

In [20]:
arr = np.array([10, 20, 30, 40, 50])

In [21]:
np.sum(arr)

np.int64(150)

In [22]:
np.mean(arr)

np.float64(30.0)

In [23]:
np.std(arr)

np.float64(14.142135623730951)

### 10. Create a 2x2 matrix A and a 2x2 matrix B. Perform matrix multiplication using np.dot() or the @ operator.

In [24]:
A = np.array([[1,2],
              [3,4]])
B = np.array([[5,6],
              [7,8]])

In [25]:
np.dot(A, B)
A @ B

array([[19, 22],
       [43, 50]])

### 11. Find the transpose of matrix A and matrix B.

In [26]:
A.T
B.T

array([[5, 7],
       [6, 8]])

### 12. Create a 3x3 array and a 1D array with 3 elements. Add the 1D array to the 2D array. Explain how broadcasting works in this operation.

In [27]:
arr2D = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
arr1D = np.array([10, 20, 30])

In [28]:
arr2D + arr1D

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39]])

### 13. Create a 4x4 array of random integers. Find the maximum, minimum, and mean of the entire array.

In [30]:
arr = np.random.randint(1, 100, size=(4, 4))
arr

array([[53, 35, 61, 26],
       [46, 92, 43, 73],
       [29, 41,  8, 97],
       [61,  8,  1, 33]], dtype=int32)

In [31]:
arr.max()

np.int32(97)

In [32]:
arr.min()

np.int32(1)

In [33]:
arr.mean()

np.float64(44.1875)

### 14. Find the row-wise and column-wise sums.

In [34]:
# Row-wise
arr.sum(axis=1)   

array([175, 254, 175, 103])

In [35]:
# column-wise
arr.sum(axis=0)   

array([189, 176, 113, 229])

### 15. Generate an array of 10 random integers between 1 and 50.

In [37]:
arr = np.random.randint(1, 51, size=10)
arr

array([15, 31,  4, 34, 26, 30, 28, 45, 24, 22], dtype=int32)

### 16. Generate a 5x5 matrix of random floats between 0 and 1.

In [38]:
arr = np.random.rand(5, 5)
arr

array([[0.21469156, 0.39610996, 0.49232036, 0.1903122 , 0.54642456],
       [0.29239673, 0.04457806, 0.91280104, 0.93024816, 0.59761016],
       [0.03170335, 0.24076496, 0.12574533, 0.57193327, 0.63356067],
       [0.69067533, 0.13154516, 0.07133252, 0.08134184, 0.41338841],
       [0.39994318, 0.95844321, 0.99626216, 0.22880163, 0.34359702]])